# Gradle / JVM
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.93
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Parchment (mapeos de nombres de parametros, opcional)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Metadatos del mod
mod_id=moin
mod_name=Moin
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.moin
mod_authors=yassona9
mod_description=Mod ficticio de Minecraft con plantas cultivables, items consumibles, una mesa de procesado y efectos personalizados. Todo el contenido es ficticio y solo funciona dentro del juego.
